/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fusesource_leveldbjni_internal_ChunkWorker */

#ifndef _Included_org_fusesource_leveldbjni_internal_ChunkWorker
#define _Included_org_fusesource_leveldbjni_internal_ChunkWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fusesource_leveldbjni_internal_ChunkWorker
 * Method:    getNextChunkNative
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ZZII)I
 */
JNIEXPORT jint JNICALL Java_org_fusesource_leveldbjni_internal_ChunkWorker_getNextChunkNative
  (JNIEnv *, jclass, jlong, jobject, jobject, jboolean, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
